name: Daily Job

on:
  workflow_dispatch:
    inputs:
      min:
        description: 'Minimum date to fetch posts from'
        required: false
        default: '2021-01-01'
  schedule:
    - cron: '0 0 * * *'

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn install

      - name: Test
        run: echo "${{ github.event.inputs.min }}"

      # - name: Fetch Posts
      #   run: npx ts-node .github/scripts/posts.mts

      # - name: Fetch Summaries/Topics
      #   run: npx ts-node .github/scripts/summaries-topics.mts
